name: check cache across workflows

on: 
  workflow_dispatch

jobs:
  fetch_cache:
    name: fetch other workflow cache
    runs-on: ubuntu-24.04
    steps:
      - name: load cache
        id: get-cache
        uses: actions/cache@v4
        with:
          path: demo-cache
          key: demo-cache-v1
      - name: cache not present
        if: steps.get-cache.outputs.cache-hit != 'true'
        run: echo "cache is not present"
      - name: cache present
        if: steps.get-cache.outputs.cache-hit == 'true'
        run: |
          echo "cache is present"
          cat demo-cache/cache.txt
