name: this for var and secrets access
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubunut-24.04
    env:
      devops-engineer: ${{ vars.devops_engineer_name }}
      db_name: ${{ vars.db_name }}
      db_pass: ${{ secrets.db_pass }}
    steps:
      - name: print var and secrets
        run: |
          echo "our devops engineer is : $devops-engineer"
          echo "db user name is $db_name"
          echo "db pass us $db_pass"
          echo "access direct var and scerets ${{ vars.db_name }}  ${{ secrets.db_pass }}"
