name: this for sms deploy poc

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      tag:
        description: Image Tag
        required: true
        type: string

jobs:
  update-parameters:
    name: update paramter.json file
    runs-on: ubuntu-24.04
    environment: "${{ github.event.inputs.environment }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.ref_name }}"
          fetch-depth: 0
          clean: false
      - name: update paramter file
        env:
          POSTGRES_ADMIN_PASSWORD:   ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          AZURE_CLIENT_SECRET:       ${{ secrets.AZURE_CLIENT_SECRET }}
          PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
        run: | 
          echo "running update json script"
          chmod +x update_paramter_json.sh
          ./update_paramter_json.sh ${{ github.event.inputs.tag }} infrastructure/environment/${{ github.event.inputs.environment }}.parameters.json
          echo "##############checking new json ############"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parameter json 
          path: infrastructure/environment/${{ github.event.inputs.environment }}.parameters.json
      - name: Dowload artifacts
        uses: actions/download-artifact@v4
        with:
          name: parameter json
      

